### ISSUE TITLE
Suggestion: Ability to set our own formula/value for item values

### ISSUE THREAD

**Issue by JoaoPaul54** [Taschenbuch/BlishHud-FarmingTracker#2]
As the title suggests, an amazing feature would be to be able to set a specific formula or value for how to calculate the value of some items (specially the ones which have no store/merch value).

For example, volatile magic has an intrinsic value as it can be changed for trophy shipments.
While I do not believe the values, such as the ones found in "fast farming community" , can be updated easily, even if only defined by us it could be incredibly powerful.

Other possibility is for us to use a formula where I could say something like 0.2*[id] and it would make the value of the item as 0.2 times the market/merch price of a certain item id.

Let me know if this is in anyway possible. I'm also a software developer so if there is anything I can do to help let me know.

**Comment by Taschenbuch** [comment]
I dont understand the 0.2*[id] part. Why would the real value of something being less than vendor/tp value?

**Comment by JoaoPaul54** [comment]
Hello. Thanks for replying
Yes, the 0.2*[id] example was indeed from a different item.

One good example of this would be the eternal ice shards.
Those can be traded at a rate of 75 for 10 items which in turn turn into an average of 20 volatile each so, the value ehre would be something along the lines of 1/75 * 10 * 20 * [value of volatile]

and in turn the value of the volatile magic is something like 45 copper each.

this value of course changes overtime depending on the trophy shipment items value so I believe it is better to either get that value from "fast farming community" if possible or if not (which  I believe it's the case) we could ahve a textbox where we cna set the value ourselves.

**Comment by Taschenbuch** [comment]
I add that to my backlog. I will probably add the ability to set a fixed value for an item/currency and not the formula approach.

**Comment by Taschenbuch** [comment]
setting a custom profit value will be part of release 4.0.0.
