### ISSUE TITLE
Suggestion: Update values based on TP entries

### ISSUE THREAD

**Issue by JoaoPaul54** [Taschenbuch/BlishHud-FarmingTracker#3]
Currently, when some item is sold on the TP we get 2 major issues.

First, the item itself is removed from the loot, this is not an issue when it is a recently dropped item but it messes up the tracker when we sell something we had before the last tracker reset.

Second, we get a minus to the gold gain (because of the TP tax) but we do not get the gold plus (even if not real) of the sale we will eventually do.

What I suggest would be to have a "real" gold and an "expected" gold.

An example situation would be if I'm farming but at some point I have to sell some stuff to get some inventory space. Currently, if it is to the merchant, it's no issue but sometimes we want to sell something on the TP right away because of margins (Specially now with a new expansion, prices change all the time of the new mats for example). At this point, we would get the TP Fee updating the real gold (since it is indeed used), but the expected gold would add the sale value. That way we can have an idea of how much we actually got on the farming session.

This does not completely remove the issue of the "old" item being removed, but at least it won't show as a major negative gain if we do sell and old item.

**Comment by Taschenbuch** [comment]
The farming tracker can only track changes on the account. It cannot distinguish between an item being salvaged, destroyed, used in crafting, sold to vendor or placed on TP as a sell listing. And it cannot distinguish what changed the raw gold. Theoretically there could be even multiple gold/item change events that happen at the same time (e.g. sell and buy the same item at a vendor instantly: 2 gold changes, 2 item changes). Those would then be recognized as a single event (no item change and the difference in raw gold between buying and selling the item). 

It would be probably possible to add a setting that will act as if every item that is lost and is tp-sellable, is considered to be set up as sell listing on the trading post. So when this item is lost, it wont affect the profits. But this has a few issues: the ones explained above and additionally the issue when you get.
For now I consider a setting like that to be very niche and it will mess up a lot other farming cases as explained above.
